import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ClientLayout from "@/components/ClientLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({

  
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        {/* Fixed Navbar */}
        <ClientLayout>
        <div className="fixed top-0 left-0 w-full z-50 bg-white shadow-md">
        <Navbar  />

        </div>

        {/* Main content with padding to avoid overlapping */}
        <main className="flex-1 lg:pt-[80px] pt-[50px] overflow-y-auto">{children}</main>

        <Footer />

        </ClientLayout>
      </body>
    </html>
  );
}
